name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
jobs:
  log-the-inputs:
    runs-on: [self-hosted]
    steps:
      - run: |
          echo "Log level: $LEVEL"
        env:
          LEVEL: 'nam ne'